Repository WildCodeSchool/lyon-js-react-march21-g1-p2, pull requests merged in 2021-04, with the labels that each got.

#4 Update issue templates for User Story
  .github/ISSUE_TEMPLATE/user_story.md
Labels: documentation

#38 WIP = merge of this week sprint
  craco.config.js
  package-lock.json
  package.json
  public/favicon.ico
  src/App.css
  src/assets/ananas.png
  src/assets/anchois.png
  src/assets/champignons.png
  src/assets/chorizos.png
  src/assets/diavola.png
  src/assets/empty-pizza.png
  src/assets/fromage.png
  src/assets/ham.png
  src/assets/herbe.png
  src/assets/jambon.png
  src/assets/margarita.png
  src/assets/mozzarella.png
  src/assets/oignon.png
  src/assets/olives.png
  src/assets/pineapple.png
  src/assets/pizza.png
  src/assets/pizzabox.png
  src/assets/regina.png
  src/assets/unite-ananas.png
  src/assets/unite-anchois.png
  src/assets/unite-champignon.png
  src/assets/unite-chorizo.png
  src/assets/unite-fond-pate.png
  src/assets/unite-fond-sauce.png
  src/assets/unite-fromage.png
  src/assets/unite-jambon.png
  src/assets/unite-mozarella.png
  src/assets/unite-oignon.png
  src/assets/unite-olive.png
  src/assets/unite-poivron.png
  src/assets/unite-roquette.png
  src/assets/unite-tomate.png
  src/components/Footer.css
  src/components/Form.js
  src/components/HeaderOrder.js
  src/components/Homepizza.js
  src/components/PizzaList.js
  src/components/formStyles.css
  src/components/pizzabox.png
  src/index.css
  src/screens/ContactAboutPage.js
  src/screens/CustomizedFoodPage.js
  src/screens/HomePage.js
  src/screens/PredefinedFoodPage.js
  src/testRequests.js
  tailwind.config.js
Labels: Ready for Prod

#49 Ingredients : increment/decrement de quantities
  .eslintrc.json
  package-lock.json
  package.json
  src/App.css
  src/assets/ham.png
  src/assets/pineapple.png
  src/assets/poivrons.png
  src/assets/roquette.png
  src/assets/tomates.png
  src/assets/unite-fond-pate.png
  src/assets/unite-fond-sauce.png
  src/assets/unite-mozzarella.png
  src/components/Footer.css
  src/components/Header.js
  src/components/IngredientsBase.js
  src/components/PizzaChange.js
  src/screens/CustomizedFoodPage.js
  src/screens/FavoriteFoodPage.js
Labels: Fixed - ready for prod

#55 header
  .env
  package-lock.json
  package.json
  public/index.html
  src/App.css
  src/App.js
  src/components/Footer.css
  src/components/Footer.js
  src/components/Header.css
  src/components/Header.js
  src/components/Main.js
  src/components/Navbar/Index.js
  src/components/Navbar/Navbar.css
  src/components/Navbar/NavbarElements.js
  src/components/Navbar/SidebarData.js
  src/components/Sidebar.js
  src/screens/HomePage.js
  src/screens/OrderPage.js
  src/screens/SignUpPage.js
  src/screens/TestPage.js
  src/screens/order.css
  yarn.lock
Labels: Ready for Prod

#56 Validation of the link between page of predefined pizzas and customized pizzas
  .env.sample
  .gitignore
  package.json
  src/App.css
  src/assets/pizzabox.svg
  src/components/Header.js
  src/components/IngredientsBase.js
  src/components/PizzaChange.js
  src/components/PizzaComposition.js
  src/components/PizzaList.js
  src/screens/CustomizedFoodPage.js
  src/screens/FavoriteFoodPage.js
  src/screens/HomePage.js
  src/screens/PredefinedFoodPage.js
Labels: Conflicts

#62 Fixed issues from this PM's PRs
  .env
  README.md
  package-lock.json
  package.json
  src/App.css
  src/components/Footer.css
  src/components/Footer.js
  src/components/Form.js
  src/components/Header.css
  src/components/Header.js
  src/components/Navbar/Navbar.css
  src/components/Navbar/SidebarData.js
  src/components/PizzaChange.js
  src/components/PizzaComposition.js
  src/components/formStyles.css
  src/components/pizzabox.png
  src/screens/CustomizedFoodPage.js
  src/screens/FavoriteFoodPage.js
  src/screens/HomePage.js
  src/screens/PredefinedFoodPage.js
  yarn.lock
Labels: Ready for Prod

#71 Added some breakpoints for the ingredients/pizza display from small screens to big ones
  .env.sample
  src/APIClient.js
  src/App.css
  src/components/Header.js
  src/components/IngredientsBase.js
  src/components/Main.js
  src/components/Navbar/NavbarElements.js
  src/components/PizzaComposition.js
  src/screens/ConfirmationPage.js
  src/screens/CustomizedFoodPage.js
  src/screens/HomePage.js
  src/screens/OrderPage.js
  src/screens/OrdersRecap.js
  src/screens/order.css
Labels: Ready for Prod

#68 Added links to get-post request between the app and api
  .env.sample
  src/APIClient.js
  src/App.css
  src/components/Header.js
  src/components/IngredientsBase.js
  src/components/Main.js
  src/components/Navbar/Index.js
  src/components/Navbar/NavbarElements.js
  src/components/PizzaComposition.js
  src/screens/ConfirmationPage.js
  src/screens/CustomizedFoodPage.js
  src/screens/HomePage.js
  src/screens/OrderPage.js
  src/screens/OrdersRecap.js
  src/screens/order.css
Labels: Ready for Prod

#76 Home text content refactored
  src/App.css
  src/screens/HomePage.js
Labels: Ready for Prod

#79 Footer / Attributions
  public/index.html
  src/App.css
  src/assets/under-construction.jpg
  src/components/Footer.js
  src/components/PizzaComposition.js
  src/components/UnderConstruction.js
  src/screens/FavoriteFoodPage.js
  src/screens/SignInPage.js
  src/screens/SignUpPage.js
  src/screens/order.css
Labels: Ready for Prod

#78 Ingred on database
  .env.sample
  README.md
  src/App.css
  src/components/IngredientsBase.js
  src/components/PizzaChange.js
  src/screens/ConfirmationPage.js
  src/screens/CustomizedFoodPage.js
Labels: Ready for Prod

#80 Css of confirmation page + added a button to empty the pizza (on pizza construction page) + colored the pizzabox image of the page with 3 buttons
  src/App.css
  src/assets/pizzabox-btn.svg
  src/assets/pizzabox.svg
  src/screens/ConfirmationPage.js
  src/screens/CustomizedFoodPage.js
Labels: Fixed - ready for prod
